[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
auto-format = false
language-server = { command = "clangd" }
file-types = ["c", "h"]

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
