[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
auto-format = false
file-types = [ "c", "h" ]
language-servers = [ "c-lsp" ]

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }
auto-format = true
language-servers = [ "python-lsp" ]

[language-server.c-lsp]
command = "clangd"

[language-server.python-lsp]
command = "pyright-langserver"
args = ["--stdio"]
